import type { CommandDef } from "./types";

/**
 * Full UX command catalog (with or without keybindings).
 * Key strings live in keymap/registry.ts: keep ids aligned.
 */
export const COMMANDS: Record<string, CommandDef> = {
  "transport.togglePlay": {
    id: "transport.togglePlay",
    category: "transport",
    label: "Play / pause",
    keywords: ["listen", "start"],
    when: "editorFocused",
    breaksFollow: true,
  },
  "transport.seek": {
    id: "transport.seek",
    category: "transport",
    label: "Seek playhead",
    when: "always",
    paletteRunnable: false,
    notes: "Args: { sec: number }",
    breaksFollow: true,
  },
  "transport.audition": {
    id: "transport.audition",
    category: "transport",
    label: "Audition Full mix / Edited stems / Original",
    when: "hasProject",
    paletteRunnable: false,
    notes: "Args: { mode: mix | fx | raw }",
  },
  "transport.stop": {
    id: "transport.stop",
    category: "transport",
    label: "Stop playback",
    keywords: ["halt"],
    when: "always",
    breaksFollow: true,
  },
  "presence.follow": {
    id: "presence.follow",
    category: "presence",
    label: "Follow",
    when: "always",
    paletteRunnable: false,
    notes: "Args: { clientId: string }",
  },
  "presence.unfollow": {
    id: "presence.unfollow",
    category: "presence",
    label: "Stop following",
    when: "following",
  },
  "tool.select": {
    id: "tool.select",
    category: "tools",
    label: "Select tool",
    when: "timelineFocused",
  },
  "tool.blade": {
    id: "tool.blade",
    category: "tools",
    label: "Blade tool",
    keywords: ["razor", "split", "knife"],
    when: "timelineAndStructural",
  },
  "review.exitCommentMode": {
    id: "review.exitCommentMode",
    category: "review",
    label: "Exit comment mode",
    when: "commentMode",
  },
  "review.toggleCommentMode": {
    id: "review.toggleCommentMode",
    category: "review",
    label: "Toggle comment mode",
    keywords: ["note", "feedback", "annotate"],
    when: "always",
  },
  "comment.resolve": {
    id: "comment.resolve",
    category: "review",
    label: "Resolve comment",
    when: "hostProjectLoaded",
    paletteRunnable: false,
    notes:
      "Args: { commentId: string, resolved: boolean, by: string } — host only; use a comment's Resolve/Reopen control",
  },
  "layout.default": {
    id: "layout.default",
    category: "layout",
    label: "Restore layout",
    when: "layoutShell",
  },
  "layout.timeline": {
    id: "layout.timeline",
    category: "layout",
    label: "Maximize timeline",
    when: "layoutShell",
  },
  "layout.text": {
    id: "layout.text",
    category: "layout",
    label: "Maximize transcript",
    when: "layoutShell",
  },
  "layout.review": {
    id: "layout.review",
    category: "layout",
    label: "Review layout",
    when: "layoutShell",
  },
  "navigation.nudgePlayheadBack": {
    id: "navigation.nudgePlayheadBack",
    category: "navigation",
    label: "Nudge playhead back",
    when: "always",
    notes: "Args: { shift?: boolean }",
    breaksFollow: true,
  },
  "navigation.nudgePlayheadForward": {
    id: "navigation.nudgePlayheadForward",
    category: "navigation",
    label: "Nudge playhead forward",
    when: "always",
    notes: "Args: { shift?: boolean }",
    breaksFollow: true,
  },
  "navigation.goToStart": {
    id: "navigation.goToStart",
    category: "navigation",
    label: "Go to start",
    when: "always",
    notes: "Home or Mod+ArrowLeft: seek playhead to 0",
    breaksFollow: true,
  },
  "navigation.goToEnd": {
    id: "navigation.goToEnd",
    category: "navigation",
    label: "Go to end",
    when: "always",
    notes: "End or Mod+ArrowRight: seek playhead to session end",
    breaksFollow: true,
  },
  "edit.bladeCut": {
    id: "edit.bladeCut",
    category: "edit",
    label: "Blade cut",
    keywords: ["razor", "split", "slice"],
    when: "canSuggestStructural",
    notes:
      "Args: { atTime?: number } → SplitAtTime at the clicked time, else the playhead (Mod+K)",
  },
  "edit.bladeCut.confirm": {
    id: "edit.bladeCut.confirm",
    category: "edit",
    label: "Confirm blade cut",
    when: "canSuggestStructural",
  },
  "edit.bladeCut.cancel": {
    id: "edit.bladeCut.cancel",
    category: "edit",
    label: "Cancel blade cut",
    when: "always",
  },
  "edit.delete": {
    id: "edit.delete",
    category: "edit",
    label: "Delete clip",
    keywords: ["remove"],
    when: "canSuggestStructural",
    notes: "Backspace/Delete: selected clip (gap left)",
  },
  "edit.clearSelection": {
    id: "edit.clearSelection",
    category: "edit",
    label: "Clear selection",
    when: "hasInspectorSelection",
    notes: "Escape: clear inspector selection (not track targeting)",
  },
  "edit.rippleDelete": {
    id: "edit.rippleDelete",
    category: "edit",
    label: "Ripple delete clip",
    keywords: ["remove", "close gap"],
    when: "canSuggestStructural",
    notes: "Mod+Backspace: selected clip (close gap)",
  },
  "edit.cutSpeech.cutAnyway": {
    id: "edit.cutSpeech.cutAnyway",
    category: "edit",
    label: "Cut anyway",
    when: "always",
    notes:
      "Apply the ripple the host held back because it cuts another speaker's speech (confirm_cut_speech)",
  },
  "edit.cutSpeech.leaveGap": {
    id: "edit.cutSpeech.leaveGap",
    category: "edit",
    label: "Leave a gap",
    when: "always",
    notes:
      "Redo the held-back ripple in gap mode: other speakers keep their speech",
  },
  "edit.cutSpeech.cancel": {
    id: "edit.cutSpeech.cancel",
    category: "edit",
    label: "Cancel cut",
    when: "always",
  },
  "edit.copy": {
    id: "edit.copy",
    category: "edit",
    label: "Copy",
    when: "hasProject",
    notes: "Mod+C: clip or transcript range → session clipboard",
  },
  "range.play": {
    id: "range.play",
    category: "edit",
    label: "Play range",
    when: "hasProject",
  },
  "range.cut": {
    id: "range.cut",
    category: "edit",
    label: "Cut selected range",
    keywords: ["remove", "delete"],
    when: "hasProject",
  },
  "range.mute": {
    id: "range.mute",
    category: "edit",
    label: "Mute selected range",
    keywords: ["silence"],
    when: "hasProject",
  },
  "range.comment": {
    id: "range.comment",
    category: "edit",
    label: "Comment on range",
    when: "hasProject",
  },
  "range.bounce": {
    id: "range.bounce",
    category: "edit",
    label: "Bounce selected range",
    keywords: ["render", "mixdown"],
    when: "hasProject",
  },
  "range.arm": {
    id: "range.arm",
    category: "edit",
    label: "Select a range",
    when: "hasProject",
  },
  "edit.cut": {
    id: "edit.cut",
    category: "edit",
    label: "Cut",
    when: "canApplyPass12",
    notes: "Mod+X: copy then ripple-delete range (host/edit)",
  },
  "edit.paste": {
    id: "edit.paste",
    category: "edit",
    label: "Paste",
    when: "canApplyPass12",
    notes: "Mod+V: duplicate clipboard at playhead (same-track)",
  },
  "track.selectAll": {
    id: "track.selectAll",
    category: "edit",
    label: "Select all tracks",
    when: "timelineFocused",
    notes: "Mod+A: target every track for blade / mute / solo",
  },
  "track.deselectAll": {
    id: "track.deselectAll",
    category: "edit",
    label: "Deselect all tracks",
    when: "timelineFocused",
    notes: "Mod+Shift+A: empty targeting (blade all dialogue)",
  },
  "track.muteToggle": {
    id: "track.muteToggle",
    category: "edit",
    label: "Toggle track mute",
    keywords: ["silence"],
    when: "hasProject",
    notes:
      "M: saved mix mute (SetTrackMute) for the host and editors; listen-only mute for other guests (Args: { trackId? })",
  },
  "track.setVolume": {
    id: "track.setVolume",
    category: "edit",
    label: "Set track volume",
    keywords: ["gain", "level", "fader"],
    when: "canEditMix",
    paletteRunnable: false,
    notes:
      "Args: { trackId?, db }: SetTrackFader, the saved volume on top of staging gain (-60 to +12 dB)",
  },
  "track.soloToggle": {
    id: "track.soloToggle",
    category: "edit",
    label: "Toggle track solo",
    keywords: ["isolate"],
    when: "hasProject",
    notes:
      "S: listen-only solo for the selected track, never saved in the mix (Args: { trackId? })",
  },
  "track.clearSolo": {
    id: "track.clearSolo",
    category: "edit",
    label: "Clear solo",
    when: "hasProject",
    notes:
      "Unsolo every track: the Solo on chip above the track headers, phone status row and Mix sheet (listen-only, no key)",
  },
  "view.zoomIn": {
    id: "view.zoomIn",
    category: "view",
    label: "Zoom in",
    keywords: ["magnify", "closer"],
    when: "timelineFocused",
    notes: "= / +: timeline focused",
    breaksFollow: true,
  },
  "view.zoomOut": {
    id: "view.zoomOut",
    category: "view",
    label: "Zoom out",
    keywords: ["wider"],
    when: "timelineFocused",
    notes: "-: timeline focused",
    breaksFollow: true,
  },
  "view.fit": {
    id: "view.fit",
    category: "view",
    label: "Fit session width",
    keywords: ["overview", "whole episode", "zoom to fit"],
    when: "timelineFocused",
    notes: "\\: timeline focused",
    breaksFollow: true,
  },
  "view.waveformZoomIn": {
    id: "view.waveformZoomIn",
    category: "view",
    label: "Waveform amplitude zoom in",
    when: "timelineFocused",
    notes: "Shift+ArrowUp: timeline focused",
    breaksFollow: true,
  },
  "view.waveformZoomOut": {
    id: "view.waveformZoomOut",
    category: "view",
    label: "Waveform amplitude zoom out",
    when: "timelineFocused",
    notes: "Shift+ArrowDown: timeline focused",
    breaksFollow: true,
  },
  "view.fitTracksHeight": {
    id: "view.fitTracksHeight",
    category: "view",
    label: "Fit tracks to window height",
    keywords: ["vertical"],
    when: "always",
    notes: "Toggle: fill the stage height, or a fixed track height",
  },
  "view.trackHeightIncrease": {
    id: "view.trackHeightIncrease",
    category: "view",
    label: "Increase track height",
    when: "timelineFocused",
    notes: "Alt+=: timeline focused; 72 / 104 / 144 / 192 / 240 px",
  },
  "view.trackHeightDecrease": {
    id: "view.trackHeightDecrease",
    category: "view",
    label: "Decrease track height",
    when: "timelineFocused",
    notes: "Alt+-: timeline focused",
  },
  "history.undo": {
    id: "history.undo",
    category: "history",
    label: "Undo",
    keywords: ["revert", "go back"],
    when: "hasProject",
  },
  "history.redo": {
    id: "history.redo",
    category: "history",
    label: "Redo",
    keywords: ["repeat"],
    when: "hasProject",
  },
  "ui.toggleCommandPalette": {
    id: "ui.toggleCommandPalette",
    category: "ui",
    label: "Commands and shortcuts",
    when: "always",
  },
  "render.refreshMix": {
    id: "render.refreshMix",
    category: "transport",
    label: "Refresh mix",
    keywords: ["render", "rerender", "premix", "update"],
    when: "canRefreshMix",
    notes: "Rebuild stems/premix (render_preview). Mod+B",
  },
  "export.bounce": {
    id: "export.bounce",
    category: "ui",
    label: "Bounce…",
    keywords: ["render", "mixdown", "stems"],
    when: "hostProjectLoaded",
    notes: "Open bounce dialog → export/bounces/. Mod+Shift+B",
  },
  "share.manage": {
    id: "share.manage",
    category: "ui",
    label: "Share…",
    keywords: ["review link", "invite", "collaborate", "guest"],
    when: "hostProjectLoaded",
    notes: "Open host share dialog: live links, create, revoke",
  },
  "record.createRoom": {
    id: "record.createRoom",
    category: "ui",
    label: "Create record room",
    keywords: ["invite", "guest", "remote", "interview"],
    when: "hostProjectLoaded",
    notes: "Mint guest + producer links in place and copy the guest link",
  },
  "record.copyGuestLink": {
    id: "record.copyGuestLink",
    category: "ui",
    label: "Copy guest link",
    keywords: ["invite", "share"],
    when: "hostProjectLoaded",
    notes: "Copy the open record room's guest link",
  },
  "record.start": {
    id: "record.start",
    category: "ui",
    label: "Start recording",
    keywords: ["capture", "mic", "microphone"],
    when: "canManageProjects",
  },
  "record.pause": {
    id: "record.pause",
    category: "ui",
    label: "Pause recording",
    when: "canManageProjects",
  },
  "record.resume": {
    id: "record.resume",
    category: "ui",
    label: "Resume recording",
    when: "canManageProjects",
  },
  "record.stop": {
    id: "record.stop",
    category: "ui",
    label: "Stop recording",
    when: "canManageProjects",
  },
  "record.land": {
    id: "record.land",
    category: "ui",
    label: "Land recording on timeline",
    when: "canManageProjects",
  },
  "record.openPanel": {
    id: "record.openPanel",
    category: "ui",
    label: "Record panel",
    when: "hostProjectLoaded",
  },
  "record.marker": {
    id: "record.marker",
    category: "ui",
    label: "Record marker",
    keywords: ["bookmark", "flag"],
    when: "recordPanelOpen",
    notes: "M while the record panel is open: posts body Marker",
  },
  "mcp.connect": {
    id: "mcp.connect",
    category: "ui",
    label: "Connect agent…",
    keywords: ["mcp", "ai", "assistant", "automation"],
    when: "canManageProjects",
    notes: "Copy local Streamable HTTP MCP URL for Cursor/Claude",
  },
  "help.diagnosticsBundle": {
    id: "help.diagnosticsBundle",
    category: "ui",
    label: "Export diagnostics…",
    keywords: ["logs", "bug report", "support", "debug"],
    when: "canManageProjects",
    notes: "Host-only sanitized diagnostics zip for bug reports",
  },
  "export.deliverables": {
    id: "export.deliverables",
    category: "ui",
    label: "Export deliverables…",
    keywords: [
      "mp3",
      "wav",
      "flac",
      "master",
      "mastering",
      "loudness",
      "lufs",
      "render",
      "final",
    ],
    when: "hostProjectLoaded",
    notes: "Master encode to export/ (same as MCP export_audio). Mod+Shift+E",
  },
  "project.new": {
    id: "project.new",
    category: "ui",
    label: "New project",
    keywords: ["create", "episode"],
    when: "canManageProjects",
    notes: "Mod+N: host only",
  },
  "project.open": {
    id: "project.open",
    category: "ui",
    label: "Open project",
    keywords: ["load", "switch", "episode"],
    when: "canManageProjects",
    notes: "Mod+O: OS dialog via local engine; paste path fallback",
  },
  "track.add": {
    id: "track.add",
    category: "edit",
    label: "New track",
    keywords: ["create", "lane"],
    when: "canIngestMedia",
    notes: "Mod+Shift+T (Shift avoids browser New Tab; Reaper uses Mod+T)",
  },
  "track.remove": {
    id: "track.remove",
    category: "edit",
    label: "Remove track",
    keywords: ["delete", "lane"],
    when: "trackInspectorSelected",
    notes:
      "Backspace/Delete when inspector track selected; confirms then RemoveTrack. Menu/inspector use skipWhen + trackId args.",
  },
  "track.reorder": {
    id: "track.reorder",
    category: "edit",
    label: "Reorder track",
    when: "canIngestMedia",
    paletteRunnable: false,
    notes: "Args: { trackId?, index }: ReorderTrack; drag headers use skipWhen",
  },
  "track.moveUp": {
    id: "track.moveUp",
    category: "edit",
    label: "Move track up",
    when: "canMoveSelectedTrackUp",
    notes: "ArrowUp: inspector track one lane up",
  },
  "track.moveDown": {
    id: "track.moveDown",
    category: "edit",
    label: "Move track down",
    when: "canMoveSelectedTrackDown",
    notes: "ArrowDown: inspector track one lane down",
  },
  "media.import": {
    id: "media.import",
    category: "edit",
    label: "Import audio",
    keywords: ["add file", "upload", "recording"],
    when: "canIngestMedia",
    notes: "Mod+I: Menu or drop on arrange; selected lane or new tracks",
  },
  "view.transcriptAnnotate": {
    id: "view.transcriptAnnotate",
    category: "view",
    label: "Annotate transcript",
    when: "always",
  },
  "transcript.adjustTiming": {
    id: "transcript.adjustTiming",
    category: "edit",
    label: "Adjust word timing",
    when: "hostProjectLoaded",
    notes: "Source-clock boundaries for the selected transcript word",
  },
  "transcript.editWordInline": {
    id: "transcript.editWordInline",
    category: "edit",
    label: "Edit focused transcript word",
    when: "hostProjectLoaded",
    paletteRunnable: false,
    notes: "F2: focused timed word in Navigate mode; hydrated host only",
  },
  "transcript.findReplace": {
    id: "transcript.findReplace",
    category: "edit",
    label: "Find and replace transcript",
    keywords: ["search", "spelling"],
    when: "hostProjectLoaded",
  },
  "transcript.correctIntent": {
    id: "transcript.correctIntent",
    category: "edit",
    label: "Correct transcript",
    keywords: ["fix", "typo", "spelling"],
    when: "hasProject",
    paletteRunnable: false,
  },
  "transcript.selectIntent": {
    id: "transcript.selectIntent",
    category: "edit",
    label: "Select transcript range",
    when: "hasProject",
    paletteRunnable: false,
  },
  "transcript.ignoreWords": {
    id: "transcript.ignoreWords",
    category: "edit",
    label: "Ignore / restore transcript words",
    when: "hasProject",
    paletteRunnable: false,
    notes:
      "Args: { trackId?, startWordIndex?, endWordIndex?, ignored? }: struck through and muted at render, no cut (#633); host-only",
  },
  "transcript.nextLowConfidence": {
    id: "transcript.nextLowConfidence",
    category: "navigation",
    label: "Next low-confidence word",
    when: "hasProject",
    notes:
      "Seek + scroll to the next word under 0.7 ASR confidence, wrapping; turns Annotate on; Correct mode selects it (#634)",
    breaksFollow: true,
  },
  "transcript.prevLowConfidence": {
    id: "transcript.prevLowConfidence",
    category: "navigation",
    label: "Previous low-confidence word",
    when: "hasProject",
    notes:
      "Seek + scroll to the previous word under 0.7 ASR confidence, wrapping; turns Annotate on; Correct mode selects it (#634)",
    breaksFollow: true,
  },
  "view.showCutAway": {
    id: "view.showCutAway",
    category: "view",
    label: "Show cut away",
    when: "always",
  },
  "edit.trimClipEdge": {
    id: "edit.trimClipEdge",
    category: "edit",
    label: "Trim clip edge",
    when: "focusedTrimHandle",
    paletteRunnable: false,
    notes: "Pointer or focused keyboard trim handles (10 ms; Shift 100 ms)",
  },
  "edit.rollClipJoin": {
    id: "edit.rollClipJoin",
    category: "edit",
    label: "Roll clip join",
    when: "canApplyPass12",
    paletteRunnable: false,
    notes: "Join diamond + transcript boundary roll both edges",
  },
  "edit.setClipFade": {
    id: "edit.setClipFade",
    category: "edit",
    label: "Set clip fade",
    when: "focusedFadeHandle",
    paletteRunnable: false,
    notes:
      "Pointer or focused keyboard fade handles (1 ms; Shift 10 ms) and paired sliders in Clip inspector",
  },
  "edit.setClipJoin": {
    id: "edit.setClipJoin",
    category: "edit",
    label: "Set clip join",
    when: "canApplyPass12",
    paletteRunnable: false,
    notes:
      "Join badge popover on the timeline; Incoming transition select and Apply transition length in the clip inspector",
  },
  "edit.moveClips": {
    id: "edit.moveClips",
    category: "edit",
    label: "Move clips",
    when: "canApplyPass12",
    paletteRunnable: false,
    notes:
      "Args: { clips: non-empty list } — pointer body drag on clip blocks (one clip or a multi-selection; not MoveSegment)",
  },
  "edit.addChapter": {
    id: "edit.addChapter",
    category: "edit",
    label: "Add chapter at playhead",
    keywords: ["marker", "chapters", "section"],
    when: "hostProjectLoaded",
    notes:
      "Args: { atTime?: number } → chapter titled from that time (the touch create menu's held time), else the playhead (AddChapter); turns the Markers layer on. Host only.",
  },
  "envelope.addPoint": {
    id: "envelope.addPoint",
    category: "edit",
    label: "Add envelope point",
    when: "canEditEnvelopes",
    paletteRunnable: false,
    notes:
      "Args: { trackId: string, atTime: number } → SetEnvelope with a point at the envelope's current level there; the touch create menu",
  },
  "comment.draftAt": {
    id: "comment.draftAt",
    category: "review",
    label: "Add comment",
    when: "canComment",
    paletteRunnable: false,
    notes:
      "Args: { atTime: number, trackId?: string } → a comment draft anchored at that time; the touch create menu",
  },
  "view.setTab": {
    id: "view.setTab",
    category: "view",
    label: "Switch editor tab",
    when: "hasProject",
    paletteRunnable: false,
    notes: "Args: { tab: DawTab }",
    breaksFollow: true,
  },
  "view.setMobileMode": {
    id: "view.setMobileMode",
    category: "view",
    label: "Switch phone mode",
    when: "hasProject",
    paletteRunnable: false,
    notes: "Args: { mode: MobileMode, destination?: MoreDestination }",
    breaksFollow: true,
  },
  "tighten.applyHit": {
    id: "tighten.applyHit",
    category: "review",
    label: "Apply tighten hit",
    keywords: ["filler", "um"],
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } → ApproveEdits",
  },
  "tighten.skipHit": {
    id: "tighten.skipHit",
    category: "review",
    label: "Skip tighten hit",
    keywords: ["filler", "ignore"],
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } → RejectEdits",
  },
  "tighten.applyAllSafe": {
    id: "tighten.applyAllSafe",
    category: "review",
    label: "Apply eligible tighten hits",
    keywords: ["filler", "fillers", "um", "uh"],
    when: "tightenPanelOpen",
    notes: "Args: { avoidHarsh?: boolean }: one ApproveEdits batch",
  },
  "tighten.previewHit": {
    id: "tighten.previewHit",
    category: "review",
    label: "Preview tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string }: rendered Suggested preview when possible",
  },
  "tighten.goToHit": {
    id: "tighten.goToHit",
    category: "review",
    label: "Go to tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string }: seek + select pending",
    breaksFollow: true,
  },
};

export function commandById(id: string): CommandDef | undefined {
  return COMMANDS[id];
}

export function listCatalogIds(): string[] {
  return Object.keys(COMMANDS);
}
