import type { CommandDef } from "./types";

/**
 * Full UX command catalog (with or without keybindings).
 * Key strings live in keymap/registry.ts — keep ids aligned.
 */
export const COMMANDS: Record<string, CommandDef> = {
  "transport.togglePlay": {
    id: "transport.togglePlay",
    category: "transport",
    label: "Play / pause",
    when: "layoutFocused",
    breaksFollow: true,
  },
  "transport.seek": {
    id: "transport.seek",
    category: "transport",
    label: "Seek playhead",
    when: "always",
    notes: "Args: { sec: number }",
    breaksFollow: true,
  },
  "transport.audition": {
    id: "transport.audition",
    category: "transport",
    label: "Audition Mix / FX / Raw",
    when: "hasProject",
    notes: "Args: { mode: mix | fx | raw }",
  },
  "transport.stop": {
    id: "transport.stop",
    category: "transport",
    label: "Stop playback",
    when: "always",
    breaksFollow: true,
  },
  "presence.follow": {
    id: "presence.follow",
    category: "presence",
    label: "Follow",
    when: "always",
    notes: "Args: { clientId: string }",
  },
  "presence.unfollow": {
    id: "presence.unfollow",
    category: "presence",
    label: "Stop following",
    when: "following",
  },
  "tool.select": {
    id: "tool.select",
    category: "tools",
    label: "Select tool",
    when: "timelineAndStructural",
  },
  "tool.blade": {
    id: "tool.blade",
    category: "tools",
    label: "Blade tool",
    when: "timelineAndStructural",
  },
  "review.exitCommentMode": {
    id: "review.exitCommentMode",
    category: "review",
    label: "Exit comment mode",
    when: "commentMode",
  },
  "review.toggleCommentMode": {
    id: "review.toggleCommentMode",
    category: "review",
    label: "Toggle comment mode",
    when: "always",
  },
  "focus.default": {
    id: "focus.default",
    category: "focus",
    label: "Focus: default layout",
    when: "layoutFocused",
  },
  "focus.timeline": {
    id: "focus.timeline",
    category: "focus",
    label: "Focus: timeline",
    when: "layoutFocused",
  },
  "focus.text": {
    id: "focus.text",
    category: "focus",
    label: "Focus: text",
    when: "layoutFocused",
  },
  "focus.review": {
    id: "focus.review",
    category: "focus",
    label: "Focus: review",
    when: "layoutFocused",
  },
  "focus.cycle": {
    id: "focus.cycle",
    category: "focus",
    label: "Cycle focus mode",
    when: "always",
  },
  "navigation.nudgePlayheadBack": {
    id: "navigation.nudgePlayheadBack",
    category: "navigation",
    label: "Nudge playhead back",
    when: "always",
    notes: "Args: { shift?: boolean }",
    breaksFollow: true,
  },
  "navigation.nudgePlayheadForward": {
    id: "navigation.nudgePlayheadForward",
    category: "navigation",
    label: "Nudge playhead forward",
    when: "always",
    notes: "Args: { shift?: boolean }",
    breaksFollow: true,
  },
  "navigation.goToStart": {
    id: "navigation.goToStart",
    category: "navigation",
    label: "Go to start",
    when: "always",
    notes: "Home or Mod+ArrowLeft — seek playhead to 0",
    breaksFollow: true,
  },
  "navigation.goToEnd": {
    id: "navigation.goToEnd",
    category: "navigation",
    label: "Go to end",
    when: "always",
    notes: "End or Mod+ArrowRight — seek playhead to session end",
    breaksFollow: true,
  },
  "edit.bladeCut": {
    id: "edit.bladeCut",
    category: "edit",
    label: "Blade cut",
    when: "canSuggestStructural",
    notes:
      "Args: { atTime?: number } → SplitAtTime at the clicked time, else the playhead (Mod+K)",
  },
  "edit.bladeCut.confirm": {
    id: "edit.bladeCut.confirm",
    category: "edit",
    label: "Confirm blade cut",
    when: "canSuggestStructural",
  },
  "edit.bladeCut.cancel": {
    id: "edit.bladeCut.cancel",
    category: "edit",
    label: "Cancel blade cut",
    when: "always",
  },
  "edit.delete": {
    id: "edit.delete",
    category: "edit",
    label: "Delete clip",
    when: "canSuggestStructural",
    notes: "Backspace/Delete — selected clip (gap left)",
  },
  "edit.clearSelection": {
    id: "edit.clearSelection",
    category: "edit",
    label: "Clear selection",
    when: "hasInspectorSelection",
    notes: "Escape — clear inspector selection (not track targeting)",
  },
  "edit.rippleDelete": {
    id: "edit.rippleDelete",
    category: "edit",
    label: "Ripple delete clip",
    when: "canSuggestStructural",
    notes: "Mod+Backspace — selected clip (close gap)",
  },
  "edit.copy": {
    id: "edit.copy",
    category: "edit",
    label: "Copy",
    when: "hasProject",
    notes: "Mod+C — clip or transcript range → session clipboard",
  },
  "edit.cut": {
    id: "edit.cut",
    category: "edit",
    label: "Cut",
    when: "canApplyPass12",
    notes: "Mod+X — copy then ripple-delete range (host/edit)",
  },
  "edit.paste": {
    id: "edit.paste",
    category: "edit",
    label: "Paste",
    when: "canApplyPass12",
    notes: "Mod+V — duplicate clipboard at playhead (same-track)",
  },
  "track.selectAll": {
    id: "track.selectAll",
    category: "edit",
    label: "Select all tracks",
    when: "timelineFocused",
    notes: "Mod+A — target every track for blade / mute / solo",
  },
  "track.deselectAll": {
    id: "track.deselectAll",
    category: "edit",
    label: "Deselect all tracks",
    when: "timelineFocused",
    notes: "Mod+Shift+A — empty targeting (blade all dialogue)",
  },
  "track.muteToggle": {
    id: "track.muteToggle",
    category: "edit",
    label: "Toggle track mute",
    when: "hasProject",
    notes: "M — viewer mute for selected track (Args: { trackId? })",
  },
  "track.soloToggle": {
    id: "track.soloToggle",
    category: "edit",
    label: "Toggle track solo",
    when: "hasProject",
    notes: "S — viewer solo for selected track (Args: { trackId? })",
  },
  "view.zoomIn": {
    id: "view.zoomIn",
    category: "view",
    label: "Zoom in",
    when: "timelineFocused",
    notes: "= / + — timeline focused",
    breaksFollow: true,
  },
  "view.zoomOut": {
    id: "view.zoomOut",
    category: "view",
    label: "Zoom out",
    when: "timelineFocused",
    notes: "- — timeline focused",
    breaksFollow: true,
  },
  "view.fit": {
    id: "view.fit",
    category: "view",
    label: "Fit session in view",
    when: "timelineFocused",
    notes: "\\ — timeline focused",
    breaksFollow: true,
  },
  "view.waveformZoomIn": {
    id: "view.waveformZoomIn",
    category: "view",
    label: "Waveform amplitude zoom in",
    when: "timelineFocused",
    notes: "Shift+ArrowUp — timeline focused",
    breaksFollow: true,
  },
  "view.waveformZoomOut": {
    id: "view.waveformZoomOut",
    category: "view",
    label: "Waveform amplitude zoom out",
    when: "timelineFocused",
    notes: "Shift+ArrowDown — timeline focused",
    breaksFollow: true,
  },
  "history.undo": {
    id: "history.undo",
    category: "history",
    label: "Undo",
    when: "hasProject",
  },
  "history.redo": {
    id: "history.redo",
    category: "history",
    label: "Redo",
    when: "hasProject",
  },
  "ui.toggleCommandPalette": {
    id: "ui.toggleCommandPalette",
    category: "ui",
    label: "Command cheatsheet",
    when: "always",
  },
  "render.refreshMix": {
    id: "render.refreshMix",
    category: "transport",
    label: "Refresh mix",
    when: "canRefreshMix",
    notes: "Rebuild stems/premix (render_preview). Mod+B",
  },
  "export.bounce": {
    id: "export.bounce",
    category: "ui",
    label: "Bounce…",
    when: "hostProjectLoaded",
    notes: "Open bounce dialog → export/bounces/. Mod+Shift+B",
  },
  "share.manage": {
    id: "share.manage",
    category: "ui",
    label: "Share…",
    when: "hostProjectLoaded",
    notes: "Open host share dialog — live links, create, revoke",
  },
  "record.start": {
    id: "record.start",
    category: "ui",
    label: "Start recording",
    when: "canManageProjects",
  },
  "record.pause": {
    id: "record.pause",
    category: "ui",
    label: "Pause recording",
    when: "canManageProjects",
  },
  "record.resume": {
    id: "record.resume",
    category: "ui",
    label: "Resume recording",
    when: "canManageProjects",
  },
  "record.stop": {
    id: "record.stop",
    category: "ui",
    label: "Stop recording",
    when: "canManageProjects",
  },
  "record.land": {
    id: "record.land",
    category: "ui",
    label: "Land recording on timeline",
    when: "canManageProjects",
  },
  "record.openPanel": {
    id: "record.openPanel",
    category: "ui",
    label: "Record panel",
    when: "hostProjectLoaded",
  },
  "record.marker": {
    id: "record.marker",
    category: "ui",
    label: "Record marker",
    when: "recordPanelOpen",
    notes: "M while the record panel is open — posts body Marker",
  },
  "mcp.connect": {
    id: "mcp.connect",
    category: "ui",
    label: "Connect agent…",
    when: "canManageProjects",
    notes: "Copy local Streamable HTTP MCP URL for Cursor/Claude",
  },
  "help.diagnosticsBundle": {
    id: "help.diagnosticsBundle",
    category: "ui",
    label: "Help…",
    when: "canManageProjects",
    notes: "Host-only sanitized diagnostics zip for bug reports",
  },
  "export.deliverables": {
    id: "export.deliverables",
    category: "ui",
    label: "Export deliverables",
    when: "hostProjectLoaded",
    notes: "Master encode to export/ (same as MCP export_audio). Mod+Shift+E",
  },
  "project.new": {
    id: "project.new",
    category: "ui",
    label: "New project",
    when: "canManageProjects",
    notes: "Mod+N — host only",
  },
  "project.open": {
    id: "project.open",
    category: "ui",
    label: "Open project",
    when: "canManageProjects",
    notes: "Mod+O — OS dialog via local engine; paste path fallback",
  },
  "track.add": {
    id: "track.add",
    category: "edit",
    label: "New track",
    when: "canIngestMedia",
    notes: "Mod+Shift+T (Shift avoids browser New Tab; Reaper uses Mod+T)",
  },
  "track.remove": {
    id: "track.remove",
    category: "edit",
    label: "Remove track",
    when: "trackInspectorSelected",
    notes:
      "Backspace/Delete when inspector track selected; confirms then RemoveTrack. Menu/inspector use skipWhen + trackId args.",
  },
  "track.reorder": {
    id: "track.reorder",
    category: "edit",
    label: "Reorder track",
    when: "canIngestMedia",
    notes:
      "Args: { trackId?, index } — ReorderTrack; drag headers use skipWhen",
  },
  "track.moveUp": {
    id: "track.moveUp",
    category: "edit",
    label: "Move track up",
    when: "canMoveSelectedTrackUp",
    notes: "ArrowUp — inspector track one lane up",
  },
  "track.moveDown": {
    id: "track.moveDown",
    category: "edit",
    label: "Move track down",
    when: "canMoveSelectedTrackDown",
    notes: "ArrowDown — inspector track one lane down",
  },
  "media.import": {
    id: "media.import",
    category: "edit",
    label: "Import audio",
    when: "canIngestMedia",
    notes: "Mod+I — Menu or drop on arrange; selected lane or new tracks",
  },
  "view.transcriptAnnotate": {
    id: "view.transcriptAnnotate",
    category: "view",
    label: "Annotate transcript",
    when: "always",
  },
  "transcript.correctIntent": {
    id: "transcript.correctIntent",
    category: "edit",
    label: "Correct transcript",
    when: "hasProject",
  },
  "transcript.selectIntent": {
    id: "transcript.selectIntent",
    category: "edit",
    label: "Select transcript range",
    when: "hasProject",
  },
  "view.showCutAway": {
    id: "view.showCutAway",
    category: "view",
    label: "Show cut away",
    when: "always",
  },
  "edit.trimClipEdge": {
    id: "edit.trimClipEdge",
    category: "edit",
    label: "Trim clip edge",
    when: "canApplyPass12",
    notes: "Pointer trim handles on clip blocks (start / end)",
  },
  "edit.rollClipJoin": {
    id: "edit.rollClipJoin",
    category: "edit",
    label: "Roll clip join",
    when: "canApplyPass12",
    notes: "Join diamond + transcript boundary roll both edges",
  },
  "edit.setClipFade": {
    id: "edit.setClipFade",
    category: "edit",
    label: "Set clip fade",
    when: "canApplyPass12",
    notes: "Pointer fade handles on clip blocks",
  },
  "edit.moveClips": {
    id: "edit.moveClips",
    category: "edit",
    label: "Move clips",
    when: "canApplyPass12",
    notes:
      "Pointer body drag on clip blocks (one clip or a multi-selection; not MoveSegment)",
  },
  "view.focusEditBoundary": {
    id: "view.focusEditBoundary",
    category: "view",
    label: "Focus edit boundary",
    when: "hasProject",
  },
  "view.focusCutAwayWord": {
    id: "view.focusCutAwayWord",
    category: "view",
    label: "Focus cut-away word",
    when: "hasProject",
  },
  "view.setTab": {
    id: "view.setTab",
    category: "view",
    label: "Switch editor tab",
    when: "hasProject",
    notes: "Args: { tab: DawTab }",
    breaksFollow: true,
  },
  "view.setMobileMode": {
    id: "view.setMobileMode",
    category: "view",
    label: "Switch phone mode",
    when: "hasProject",
    notes: "Args: { mode: MobileMode, destination?: MoreDestination }",
    breaksFollow: true,
  },
  "tighten.applyHit": {
    id: "tighten.applyHit",
    category: "review",
    label: "Apply tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } → ApproveEdits",
  },
  "tighten.skipHit": {
    id: "tighten.skipHit",
    category: "review",
    label: "Skip tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } → RejectEdits",
  },
  "tighten.applyAllSafe": {
    id: "tighten.applyAllSafe",
    category: "review",
    label: "Apply eligible tighten hits",
    when: "tightenPanelOpen",
    notes: "Args: { avoidHarsh?: boolean } — one ApproveEdits batch",
  },
  "tighten.previewHit": {
    id: "tighten.previewHit",
    category: "review",
    label: "Preview tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } — Suggested skip when possible",
  },
  "tighten.goToHit": {
    id: "tighten.goToHit",
    category: "review",
    label: "Go to tighten hit",
    when: "tightenPanelOpen",
    notes: "Args: { id?: string } — seek + select pending",
    breaksFollow: true,
  },
};

export function commandById(id: string): CommandDef | undefined {
  return COMMANDS[id];
}

export function listCatalogIds(): string[] {
  return Object.keys(COMMANDS);
}
