"""Registry of MCP/CLI tool time-parameter semantics (source vs timeline clock)."""

from __future__ import annotations

from typing import Literal

TimebaseKind = Literal["source", "timeline", "relative", "na"]

# Keys are MCP tool handler function names (``mcp.tool()(fn)``).
TOOL_TIMEBASE: dict[str, TimebaseKind] = {
    # Play / audition - processed stems use session timeline seconds.
    "play_audio_tool": "timeline",
    "play_compose_tool": "timeline",
    "play_transcript_query_tool": "timeline",
    "play_compare_tool": "timeline",
    "play_ab_tool": "timeline",
    "play_ab_wavs_tool": "na",
    "play_pending_preview_tool": "timeline",
    "audition_context_tool": "timeline",
    # Edit decisions and transcript words are stored in source media seconds.
    "cut_time_range_tool": "source",
    "cut_text_match_tool": "source",
    "cut_utterance_tool": "source",
    "cut_words_tool": "source",
    "preview_inaudible_cut_tool": "source",
    "suggest_handoff_cut_tool": "timeline",
    "join_quality_tool": "timeline",
    "join_qa_sweep_tool": "timeline",
    "join_label_tool": "source",
    "update_pending_edit_tool": "source",
    "revert_applied_edit_tool": "na",
    "move_segment_tool": "timeline",
    "move_clips_tool": "timeline",
    "move_by_text_tool": "source",
    "duplicate_segment_tool": "timeline",
    "overlap_duplicates_tool": "timeline",
    "insert_gap_tool": "timeline",
    "fade_joins_tool": "na",
    "crossfade_joins_tool": "na",
    "set_join_mode_tool": "na",
    "set_effect_bypass_tool": "na",
    "set_word_suppressed_tool": "source",
    "fill_with_room_tone_tool": "timeline",
    "strip_silence_tool": "source",
    "shorten_gaps_tool": "source",
    "ripple_delete_tool": "timeline",
    "ripple_delete_text_tool": "source",
    "audio_diagnostics_tool": "timeline",
    "reconcile_transcript_tool": "source",
    "bleed_words_tool": "source",
    "apply_bleed_suppression_tool": "source",
    "apply_transcript_gate_tool": "timeline",
    "low_audibility_words_tool": "source",
    "low_confidence_words_tool": "source",
    "gate_overreach_tool": "source",
    "ingest_import_folder_tool": "na",
    "ingest_suggest_alignment_tool": "source",
    "ingest_verify_alignment_tool": "source",
    "add_chapter_tool": "timeline",
    "remove_chapter_tool": "na",
    "add_comment_tool": "timeline",
    "list_comments_tool": "na",
    "get_comment_tool": "na",
    "update_comment_tool": "timeline",
    "resolve_comment_tool": "na",
    "add_comment_action_tool": "na",
    "set_comment_action_done_tool": "na",
    "delete_comment_tool": "na",
    "speaker_score_tool": "source",
    "speaker_compare_window_tool": "source",
    "speaker_label_tool": "source",
    "speaker_set_count_tool": "na",
    "speaker_attribute_tool": "source",
    "speaker_gate_track_tool": "source",
    "speaker_compare_pair_tool": "source",
    "history_undo": "na",
    "history_redo": "na",
    "history_list": "na",
    "history_status_tool": "na",
    "history_goto_tool": "na",
    "history_diff_tool": "na",
    "history_record": "na",
    "list_applied_edits_tool": "timeline",
    "render_status_tool": "na",
    "precorrect_transcript_tool": "na",
    "transcript_refine_status_tool": "na",
    "transcript_refine_brief_tool": "na",
    "transcript_refine_done_tool": "na",
    "transcript_refine_waive_tool": "na",
    "pipeline_run": "na",
    "bounce_audio_tool": "timeline",
}

TIME_PARAM_NAMES = frozenset(
    {
        "start",
        "end",
        "start_s",
        "end_s",
        "start_sec",
        "end_sec",
        "time",
        "analysis_start_sec",
        "window_start_sec",
        "insert_at",
        "timeline_start",
        "timeline_end",
        "join_sec",
        "cut_start",
        "cut_end",
    }
)
