from typing import TYPE_CHECKING

from podcast_mcp.util.lazy_exports import resolve_export

if TYPE_CHECKING:
    from podcast_mcp.services.collaboration.guest_progress import (
        guest_progress_hub,
        guest_ws_progress_sink,
        reset_guest_progress_hub,
        scrub_guest_progress_text,
    )
    from podcast_mcp.services.collaboration.record_share import record_bootstrap
    from podcast_mcp.services.collaboration.review import ReviewService
    from podcast_mcp.services.collaboration.session_control import SessionControlService
    from podcast_mcp.services.collaboration.share import (
        ShareService,
        drop_absolute_path_strings,
        guest_selects_transcript_words,
        lookup_share,
        open_share_workspace,
        require_share_cap,
        resolve_share_audio_redirect,
        sanitize_guest_document_event,
        sanitize_guest_session_event,
        sanitize_guest_session_snapshot,
        share_add_comment,
        share_add_reply,
        share_allows_mcp,
        share_audio_path,
        share_audition_context_cached,
        share_audition_context_image,
        share_audition_context_image_cached,
        share_audition_context_info,
        share_daw_audio_path,
        share_daw_meta,
        share_daw_project_view,
        share_daw_waveform_snap,
        share_daw_waveform_status,
        share_daw_waveform_tiles,
        share_episode_name,
        share_pending_cut_suggestion,
        share_pending_preview_image,
        share_pending_preview_image_cached,
        share_pending_preview_info,
        share_pending_preview_wav,
        share_pending_preview_wav_cached,
        share_project_view,
        share_proxy_chunk_path,
        share_proxy_manifest,
        share_selected_range_audio,
        share_set_action_done,
        share_upload_media,
    )
    from podcast_mcp.services.collaboration.share_page import (
        build_share_head_tags,
        inject_share_document_head,
        render_record_spa_html,
        render_share_spa_html,
        share_public_origin,
    )
    from podcast_mcp.services.collaboration.tunnel import run_tunnel_sync

__all__ = [
    "ReviewService",
    "SessionControlService",
    "ShareService",
    "build_share_head_tags",
    "drop_absolute_path_strings",
    "guest_progress_hub",
    "guest_selects_transcript_words",
    "guest_ws_progress_sink",
    "inject_share_document_head",
    "lookup_share",
    "open_share_workspace",
    "record_bootstrap",
    "render_record_spa_html",
    "render_share_spa_html",
    "require_share_cap",
    "reset_guest_progress_hub",
    "resolve_share_audio_redirect",
    "run_tunnel_sync",
    "sanitize_guest_document_event",
    "sanitize_guest_session_event",
    "sanitize_guest_session_snapshot",
    "scrub_guest_progress_text",
    "share_add_comment",
    "share_add_reply",
    "share_allows_mcp",
    "share_audio_path",
    "share_audition_context_cached",
    "share_audition_context_image",
    "share_audition_context_image_cached",
    "share_audition_context_info",
    "share_daw_audio_path",
    "share_daw_meta",
    "share_daw_project_view",
    "share_daw_waveform_snap",
    "share_daw_waveform_status",
    "share_daw_waveform_tiles",
    "share_episode_name",
    "share_pending_cut_suggestion",
    "share_pending_preview_image",
    "share_pending_preview_image_cached",
    "share_pending_preview_info",
    "share_pending_preview_wav",
    "share_pending_preview_wav_cached",
    "share_project_view",
    "share_proxy_chunk_path",
    "share_proxy_manifest",
    "share_public_origin",
    "share_selected_range_audio",
    "share_set_action_done",
    "share_upload_media",
]

_MODULE_BY_NAME = {
    "ReviewService": "review",
    "SessionControlService": "session_control",
    "ShareService": "share",
    "build_share_head_tags": "share_page",
    "drop_absolute_path_strings": "share",
    "guest_progress_hub": "guest_progress",
    "guest_selects_transcript_words": "share",
    "guest_ws_progress_sink": "guest_progress",
    "inject_share_document_head": "share_page",
    "lookup_share": "share",
    "open_share_workspace": "share",
    "record_bootstrap": "record_share",
    "render_record_spa_html": "share_page",
    "render_share_spa_html": "share_page",
    "require_share_cap": "share",
    "reset_guest_progress_hub": "guest_progress",
    "resolve_share_audio_redirect": "share",
    "run_tunnel_sync": "tunnel",
    "sanitize_guest_document_event": "share",
    "sanitize_guest_session_event": "share",
    "sanitize_guest_session_snapshot": "share",
    "scrub_guest_progress_text": "guest_progress",
    "share_add_comment": "share",
    "share_add_reply": "share",
    "share_allows_mcp": "share",
    "share_audio_path": "share",
    "share_audition_context_cached": "share",
    "share_audition_context_image": "share",
    "share_audition_context_image_cached": "share",
    "share_audition_context_info": "share",
    "share_daw_audio_path": "share",
    "share_selected_range_audio": "share",
    "share_daw_meta": "share",
    "share_daw_project_view": "share",
    "share_daw_waveform_snap": "share",
    "share_daw_waveform_status": "share",
    "share_daw_waveform_tiles": "share",
    "share_episode_name": "share",
    "share_pending_cut_suggestion": "share",
    "share_pending_preview_image": "share",
    "share_pending_preview_image_cached": "share",
    "share_pending_preview_info": "share",
    "share_pending_preview_wav": "share",
    "share_pending_preview_wav_cached": "share",
    "share_project_view": "share",
    "share_proxy_chunk_path": "share",
    "share_proxy_manifest": "share",
    "share_public_origin": "share_page",
    "share_set_action_done": "share",
    "share_upload_media": "share",
}


def __getattr__(name: str) -> object:
    return resolve_export(name, package=__name__, namespace=globals(), modules=_MODULE_BY_NAME)
