/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-declaration-strict-value", "stylelint-no-px"],
  ignoreFiles: ["src/styles/theme/**", "public/brand-tokens.css"],
  rules: {
    // Motion times with --motion-* tokens (docs/design-tokens.md § Motion);
    // tests/test_css_policy.py also checks the no-preference guard.
    "declaration-property-unit-disallowed-list": {
      "/^(-webkit-)?(transition|animation)/": ["ms", "s"],
    },
    "scale-unlimited/declaration-strict-value": [
      [
        "/color$/",
        "/^(background|background-color|border-color|outline-color|fill|stroke)$/",
        "box-shadow",
        "border",
        "border-top",
        "border-right",
        "border-bottom",
        "border-left",
        "outline",
        "text-shadow",
        "/^padding/",
        "/^margin/",
        "font-size",
        "gap",
        "row-gap",
        "column-gap",
        "/^border-radius/",
      ],
      {
        ignoreValues: {
          "": [
            "currentColor",
            "transparent",
            "inherit",
            "initial",
            "unset",
            "none",
            "auto",
            "solid",
            "dashed",
            "dotted",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
            "hidden",
            "/^0$/",
            "/^0 /",
            "/ 0$/",
            "/ 0 /",
            "/^1px$/",
            "/^-1px$/",
            "/^1px /",
            "/^-1px /",
          ],
          "/color$/": [
            "currentColor",
            "transparent",
            "inherit",
            "initial",
            "unset",
            "none",
          ],
          "/^(background|background-color|border-color|outline-color|fill|stroke)$/":
            ["currentColor", "transparent", "inherit", "none"],
          "box-shadow": [
            "none",
            "inherit",
            "inset",
            "/^0$/",
            "/^0 /",
            "/^inset /",
            "/^1px$/",
            "/^-?[0-9.]+(%|px|em|rem)$/",
            "/^-?[0-9.]+(%|px|em|rem)? /",
            "/^-?[0-9.]+(%|px|em|rem)?,/",
          ],
          "/^border/": [
            "none",
            "solid",
            "dashed",
            "dotted",
            "transparent",
            "currentColor",
            "/^0$/",
            "/^1px$/",
            "/^-1px$/",
            "/^1px /",
            "/^-1px /",
          ],
          outline: [
            "none",
            "solid",
            "transparent",
            "currentColor",
            "/^0$/",
            "/^1px$/",
            "/^-1px$/",
            "/^1px /",
            "/^-1px /",
          ],
          "text-shadow": ["none", "/^0 /"],
          "/^border-radius/": ["/^0$/", "50%", "inherit", "/^1px$/"],
        },
        disableFix: true,
        expandShorthand: false,
        ignoreFunctions: {
          "/color$/": false,
          "/^(background|background-color|border-color|outline-color|fill|stroke)$/": false,
          "box-shadow": true,
          border: false,
          "border-top": false,
          "border-right": false,
          "border-bottom": false,
          "border-left": false,
          outline: false,
          "text-shadow": true,
          "/^padding/": true,
          "/^margin/": true,
          "font-size": false,
          gap: true,
          "row-gap": true,
          "column-gap": true,
          "/^border-radius/": true,
        },
      },
    ],
    "color-function-notation": null,
    "color-function-alias-notation": null,
    "color-hex-length": null,
    "alpha-value-notation": null,
    "hue-degree-notation": null,
    "lightness-notation": null,
    "import-notation": null,
    "custom-property-pattern": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "keyframes-name-pattern": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "rule-empty-line-before": null,
    "comment-empty-line-before": null,
    "custom-property-empty-line-before": null,
    "declaration-empty-line-before": null,
    "at-rule-empty-line-before": null,
    "media-feature-range-notation": null,
    "declaration-property-value-no-unknown": null,
    "property-no-vendor-prefix": null,
    "value-no-vendor-prefix": null,
    "selector-no-vendor-prefix": null,
    "function-no-unknown": null,
    "property-no-deprecated": null,
    "declaration-no-important": true,
    /* Hairline allowlist: sync with tests/test_css_policy.py (`abs(...) == 1`). */
    "meowtec/no-px": [true, { ignore: ["1px", "-1px"] }],
    "media-feature-name-disallowed-list": [
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
    ],
    "at-rule-disallowed-list": ["layer"],
    "declaration-property-value-disallowed-list": {
      "font-size": ["/62\\.5%/"],
    },
  },
};
